services:
  - type: web
    name: stwag-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_NAME
        value: STWAG
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:V10CocZFLBhef6yF9KUXFSjg/+JoMV/whbTs0qPwTRo=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-stwag.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: stwag_api
      - key: DB_USERNAME
        value: stwag
      - key: DB_PASSWORD
        value: alwaysdata@n0t4u2c
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_SCHEME
        value: null
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: ediangca22@gmail.com
      - key: MAIL_PASSWORD
        value: nrvpqdtqbltlhydw
      - key: MAIL_FROM_ADDRESS
        value: ediangca22@gmail.com
      - key: MAIL_FROM_NAME
        value: STWAG
      

        

