<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->string('user_id')->primary();
            $table->string('firstname');
            $table->string('lastname');
            $table->dateTime('birthdate');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->string('type'); //member, admin, etc.
            $table->string('referencecode'); //generated by the system
            $table->string('uplinecode');
            $table->integer('level'); // 1, 2, 3 and if type is member it will automatically generated depended on the uplinecode
            $table->integer('avatar')->default(0);
            $table->string('uuid')->unique();
            $table->string('devicenmodel');
            $table->rememberToken();
            $table->timestamps();
        });

        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        Schema::create('sessions', function (Blueprint $table) {
            $table->string('session_id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });

        // Schema::create('members', function (Blueprint $table) {
        //     $table->string('member_id')->primary();
        //     $table->foreignId('user_id')->index();
        //     $table->string('firstname', 45);
        //     $table->string('lastname', 45);
        //     $table->char('mi')->nullable();
        //     $table->string('type');
        //     $table->integer('level');
        //     $table->string('referencecode')->unique();
        //     $table->string('uplinecode');
        //     $table->timestamps();
        // });

        Schema::create('device', function (Blueprint $table) {
            $table->id('deviceid');
            $table->string('devicename', 45);
            $table->foreignId('user_id')->index();
            $table->timestamps();
        });
        
        Schema::create('wallets', function (Blueprint $table) {
            $table->id('wallet_id');
            $table->foreignId('user_id')->index();
            $table->double('points');  
            $table->string('ref_id', 45)->nullable(); //result_id, bet_id, etc.
            // $table->string('source', 45); //Source of points (Bunos, TopUp, Incentives, Cashback (Unwithdrawable), Bet (Negative), Winning, Withdraw (negative)
            $table->enum('source', ['BUN','TOP','INC','CBK','BET','WIN','WTH'])->default('BET');
            $table->boolean('withdrawableFlag')->default(0); // 0 = not confirmed, 1 = confirmed
            $table->boolean('confirmFlag')->default(0); // 0 = not confirmed, 1 = confirmed
            $table->timestamps();
        });
        

        // Schema::create('wallets', function (Blueprint $table) {
        //     $table->string('wallet_id')->primary();
        //     $table->foreignId('user_id')->index();
        //     $table->timestamps();
        // });

        Schema::create('wallet_item', function (Blueprint $table) {
            $table->string('walletitem_id')->primary();
            $table->foreignId('user_id')->index();
            $table->double('points')->default(0);
            $table->timestamps();
        });
        
        Schema::create('topups', function (Blueprint $table) {
            $table->id('topup_id');
            $table->foreignId('user_id')->index();
            $table->double('points');  
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('sessions');
        Schema::dropIfExists('members');
        Schema::dropIfExists('device');
        Schema::dropIfExists('wallets');
        Schema::dropIfExists('wallet_item');
    }
};
